mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('', HomeView.as_view(), name='home'),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('vonly/', views.TodoVueOnlyTV.as_view(), name='vonly'),

    path('create/', views.TodoCV.as_view(), name='create'),
    path('list/', views.TodoLV.as_view(), name='list'),
    path('<int:pk>/delete/', views.TodoDelV.as_view(), name='delete'),

]

todo/models.py
from django.db import models

class Todo(models.Model):
    name = models.CharField('NAME', max_length=5, blank=True)
    todo = models.CharField('TODO', max_length=50)

    def __str__(self):
        return self.todo


    def save(self, force_insert=False, force_update=False, using=None, update_field=None):
        if not self.name:
            self.name = '홍길동'
        super().save()

mysite/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

todo/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DeleteView

from todo.models import Todo


class TodoVueOnlyTV(TemplateView):
    template_name = 'todo/todo_vue_only.html'

class TodoCV(CreateView):
    model = Todo
    fields = '__all__'
    template_name = 'todo/todo_form.html'
    success_url = reverse_lazy('todo:list')

class TodoLV(ListView):
    model = Todo
    template_name = 'todo/todo_list.html'

class TodoDelV(DeleteView):
    model = Todo
    template_name = 'todo/todo_confirm_delete.html'
    success_url = reverse_lazy('todo:list')

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ko">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}home.html{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    {% block extra-style %}{% endblock %}

</head>

<body style="padding-top:90px;">

<!-- Main Menu -->
<nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">

    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Vue-Django System</span>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'todo:vonly' %}">VueOnly</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'todo:create' %}">DjangoOnly</a></li>
            <li class="nav-item mx-1 btn btn-primary">
{#                <a class="nav-link text-white" href="{% url 'todo:mixin' %}">DjangoMixin</a></li>#}

            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    <div class="dropdown-divider"></div>
                </div>
            </li>
        </ul>

        <form class="form-inline my-2">
            <input class="form-control mr-sm-2" type="search" placeholder="Search">
        </form>

        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'home' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'home' %}">Register</a>
                </div>
            </li>
        </ul>

    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% block extra-script %}{% endblock %}

</body>

</html>

templates/home.html
{% extends 'base.html' %}

todo/templates/todo/todo_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vue-Django ToDo App</title>

  <style>
    body {
      text-align: center;
      background-color: #ddd;
    }

    .inputBox {
      margin: auto;
      width: 70%;
      background: white;
      height: 50px;
      border-radius: 50px;
      line-height: 50px;
    }

    .inputBox .name {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 70px;
      padding-left: 20px;
    }

    .inputBox .item {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 400px;
      margin-left: 50px;
      padding-left: 20px;
    }

    .todoList {
      list-style: none;
      padding: 10px 0;
      text-align: left;
    }

    .todoList li {
      display: flex;
      height: 50px;
      line-height: 50px;
      margin: 0.5rem 0;
      padding: 0 0.9rem;
      background: white;
      border-radius: 5px;
    }

    .removeBtn {
      margin-left: auto;
      font-size: 20px;
    }
  </style>
</head>

<body>
<div id='app'>
  <h1>Todo delete</h1>
  <p>정말로 삭제하시겠습니까?</p>
  <br>
  <form action="." method="post">{% csrf_token %}
    <button type="submit">
    confirm
    </button>
  </form>
</div>


</body>
</html>

todo/templates/todo/todo_form.html
{%    %}
  <title>Vue-Django ToDo App</title>

  <style>
    body {
      text-align: center;
      background-color: #ddd;
    }

    .inputBox {
      margin: auto;
      width: 70%;
      background: white;
      height: 50px;
      border-radius: 50px;
      line-height: 50px;
    }

    .inputBox .name {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 70px;
      padding-left: 20px;
    }

    .inputBox .item {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 400px;
      margin-left: 50px;
      padding-left: 20px;
    }

    .todoList {
      list-style: none;
      padding: 10px 0;
      text-align: left;
    }

    .todoList li {
      display: flex;
      height: 50px;
      line-height: 50px;
      margin: 0.5rem 0;
      padding: 0 0.9rem;
      background: white;
      border-radius: 5px;
    }

    .removeBtn {
      margin-left: auto;
      font-size: 20px;
    }
  </style>
</head>

<body>
<div id='app'>

  <h1>My Todo App !</h1>
  <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
  <br>

  <form class="inputBox" action="." method="post"> {% csrf_token %}
    <input class="name" type="text" placeholder="name ..." name="name">
    <input class="item" type="text" placeholder="type anything welcomed ..."
           name="todo">
    <button type="submit" class="btn btn-info btn-sm">ADD</button>
  </form>

</div>


</body>
</html>


todo/templates/todo/todo_list.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vue-Django ToDo App</title>

  <style>
    body {
      text-align: center;
      background-color: #ddd;
    }

    .inputBox {
      margin: auto;
      width: 70%;
      background: white;
      height: 50px;
      border-radius: 50px;
      line-height: 50px;
    }

    .inputBox .name {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 70px;
      padding-left: 20px;
    }

    .inputBox .item {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 400px;
      margin-left: 50px;
      padding-left: 20px;
    }

    .todoList {
      list-style: none;
      padding: 10px 0;
      text-align: left;
    }

    .todoList li {
      display: flex;
      height: 50px;
      line-height: 50px;
      margin: 0.5rem 0;
      padding: 0 0.9rem;
      background: white;
      border-radius: 5px;
    }

    .removeBtn {
      margin-left: auto;
      font-size: 20px;
    }
  </style>
</head>

<body>
<div id='app'>

  <h1>My Todo App !</h1>
  <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
  <br>

  <ul class="todoList">
    {% for todo in object_list %}
    <li>
      <span>{{ todo.name }} ::: {{ todo.todo }}</span>
      <span class="removeBtn" ><a href="{% url 'todo:delete' todo.id %}">&#x00D7</a></span>
    </li>
    {% endfor %}
  </ul>
</div>



</body>
</html>

todo/templates/todo/todo_vue_only.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vue-Django ToDo App</title>

  <style>
    body {
      text-align: center;
      background-color: #ddd;
    }

    .inputBox {
      margin: auto;
      width: 70%;
      background: white;
      height: 50px;
      border-radius: 50px;
      line-height: 50px;
    }

    .inputBox .name {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 70px;
      padding-left: 20px;
    }

    .inputBox .item {
      border-style: none;
      border-bottom: 1px solid #ddd;
      width: 400px;
      margin-left: 50px;
      padding-left: 20px;
    }

    .todoList {
      list-style: none;
      padding: 10px 0;
      text-align: left;
    }

    .todoList li {
      display: flex;
      height: 50px;
      line-height: 50px;
      margin: 0.5rem 0;
      padding: 0 0.9rem;
      background: white;
      border-radius: 5px;
    }

    .removeBtn {
      margin-left: auto;
      font-size: 20px;
    }
  </style>
</head>

<body>
<div id='app'>

  <h1>My Todo App !</h1>
  <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
  <br>

  <div class="inputBox">
    <input class="name" type="text" placeholder="name ..." v-model="name">
    <input class="item" type="text" placeholder="type anything welcomed ..." v-model="newTodoItem" v-on:keyup.enter="add_todo()">
    <button v-on:click="add_todo()">ADD</button>
  </div>

  <ul class="todoList">
    <li v-for="todo, index in todoItems">
      <span>{ todo.name }::: { todo.item }</span>
      <span class="removeBtn" v-on:click="remove_todo(index)">&#x00D7</span>
    </li>
  </ul>
</div>

<script src='https://unpkg.com/vue/dist/vue.min.js'></script>
<script>
    var vm = new Vue({
        delimiters: ['{','}'],
        el: '#app',
        data: {
            name: '',
            newTodoItem: '',
            todoItems: [
                {name: '김석훈', item: 'Django 와 Vue.js 연동 프로그램을 만들고 있습니다.'},
                {name: '홍길동', item: '이름을 안쓰면 홍길동으로 나와요...'},
                {name: '이순신', item: '신에게는 아직 열두 척의 배가 있사옵니다.'},
                {name: '성춘향', item: '그네 타기'},
            ],
        },
        methods: {
            add_todo: function () {
                console.log("add todo");
                if (this.newTodoItem == '') return;
                if (this.name == '') this.name = '홍길동';

                this.todoItems.push({name: this.name, item: this.newTodoItem});
                this.name = '';
                this.newTodoItem = '';
            },
            remove_todo: function (index) {
                console.log("remove todo");
                this.todoItems.splice(index, 1)
            }

        },
    })
</script>

</body>
</html>